### ISSUE TITLE
GH Workflow Error: Windows Support

### ISSUE THREAD

**Issue by p8h-74** [Labfox/whatsfly#83]
When will the build error on Windows x64 be fixed?

**Comment by Labfox** [comment]
For now, the error isn't with GitHub workflows, but more with simply building Whatsfly for Windows, and fixing this problem seems to come from other libraries, so it would need direct development on Windows, and I personally don't have a test machine to do that. So feel free to make a pull request if you get it working.

**Comment by Labfox** [comment]
I've tweaked a bit the workflow, it seems to build correctly, can you test on Windows ?

**Comment by Eikosa** [comment]
> I've tweaked a bit the workflow (apparently the libraries got updated since the last time I tried), it seems to build correctly, can you test on Windows ?

I got this error

```python
File ~\AppData\Roaming\Python\Python310\site-packages\whatsfly\dependencies\builder.py:106, in ensureUsableBinaries()
    [105](https://untitled+.vscode-resource.vscode-cdn.net/~/AppData/Roaming/Python/Python310/site-packages/whatsfly/dependencies/builder.py:105) if rq.status_code != 200:
--> [106](https://untitled+.vscode-resource.vscode-cdn.net/~/AppData/Roaming/Python/Python310/site-packages/whatsfly/dependencies/builder.py:106)     raise RuntimeError(
    [107](https://untitled+.vscode-resource.vscode-cdn.net/~/AppData/Roaming/Python/Python310/site-packages/whatsfly/dependencies/builder.py:107)         f"Server responded with {rq.status_code}, impossible to find the binaries, giving up"
    [108](https://untitled+.vscode-resource.vscode-cdn.net/~/AppData/Roaming/Python/Python310/site-packages/whatsfly/dependencies/builder.py:108)     )
    [109](https://untitled+.vscode-resource.vscode-cdn.net/~/AppData/Roaming/Python/Python310/site-packages/whatsfly/dependencies/builder.py:109) open(f"{root_dir.replace('dependencies', '')}/dependencies/{get_dll_filename()}", "wb").write(rq.content)

RuntimeError: Server responded with 404, impossible to find the binaries, giving up
...
    [118](https://untitled+.vscode-resource.vscode-cdn.net/~/AppData/Roaming/Python/Python310/site-packages/whatsfly/dependencies/builder.py:118)     )
    [119](https://untitled+.vscode-resource.vscode-cdn.net/~/AppData/Roaming/Python/Python310/site-packages/whatsfly/dependencies/builder.py:119) except Exception:
--> [120](https://untitled+.vscode-resource.vscode-cdn.net/~/AppData/Roaming/Python/Python310/site-packages/whatsfly/dependencies/builder.py:120)     raise RuntimeError("Impossible to find the binaries, giving up")

RuntimeError: Impossible to find the binaries, giving up
```

**Comment by Labfox** [comment]
can you run this ?:

```python
import whatsfly.dependencies.builder

whatsfly.dependencies.builder.get_dll_filename()
```

**Comment by Labfox** [comment]
What's the result of ```platform.system()``` and ```platform.machine()``` ?

**Comment by Labfox** [comment]
Just noticed you were using Whatsfly 0.1.3. This was fixed in 0.2.1. You can install with pip using [whatsfly-labfox](https://pypi.org/project/whatsfly-labfox/)

**Comment by p8h-74** [comment]
> Just noticed you were using Whatsfly 0.1.3. This was fixed in 0.2.1. You can install with pip using [whatsfly-labfox](https://pypi.org/project/whatsfly-labfox/)

How do it this ?

**Comment by p8h-74** [comment]
> Только что заметил, что вы используете Whatsfly 0.1.3. Это было исправлено в версии 0.2.1. Вы можете установить с помощью pip с помощью [whatsfly-labfox](https://pypi.org/project/whatsfly-labfox/)

`Traceback (most recent call last):
  File "C:\DOP FILES\Test\main.py", line 1, in <module>
    import whatsfly.dependencies.builder
  File "C:\DOP FILES\Test\venv\Lib\site-packages\whatsfly\__init__.py", line 18, in <module>
    ensureUsableBinaries()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\DOP FILES\Test\venv\Lib\site-packages\whatsfly\dependencies\builder.py", line 87, in ensureUsableBinaries
    build()
    ~~~~~^^
  File "C:\DOP FILES\Test\venv\Lib\site-packages\whatsfly\dependencies\builder.py", line 71, in build
    status_code = subprocess.check_call(go_build_cmd, cwd=f"whatsfly/dependencies")  File "C:\Users\Дом\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 414, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\Дом\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 395, in call
    with Popen(*popenargs, **kwargs) as p:
         ~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 1036, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        pass_fds, cwd, env,
                        ^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
                        gid, gids, uid, umask,
                        ^^^^^^^^^^^^^^^^^^^^^^
                        start_new_session, process_group)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 1548, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
                             # no special security
                             ^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
                             cwd,
                             ^^^^
                             startupinfo)
                             ^^^^^^^^^^^^
NotADirectoryError: [WinError 267] Неверно задано имя папки`

**Comment by Labfox** [comment]
# ? 

It seems like your python/windows install is buggy. Also it is `whatsfly-Labfox`, not `whatsfly`

**Comment by Abdurrafey-Siddiqui** [comment]
Hi @Labfox 

Great thanks for the project. The docs seem to be outdated and hence why even I noticed that whatsfly was installed when following the installation steps

When running pip install whatsfly-labfox it installed the correct one

**Comment by Labfox** [comment]
Updated the docs!
